# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/SharingCitiesDashboard/Frontend

    docker:
      - image: circleci/node:8
    branches:
      only:
        - master # list of branches to build
        - /testintegrations2/ # or regexes

    steps:
      - checkout

      - run:
          name: Setup Dependencies
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
        
      # run tests!
      - run: npm test
