FROM python:3.7

# Create a Work Directory for the Code
RUN mkdir /code
WORKDIR /code
COPY Analytics/requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y redis-server