version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-DB
  api:
    build:
      context: .
      dockerfile: Dockerfile-API
    command: bash -c "python manage.py gunicorn & service redis-server start & celery -A manage.celery_task worker -l info"
    volumes:
      - ./Analytics/:/Analytics
    ports:
      - "5000:5000"
      - "6379:6379"
    depends_on:
      - db
  ui:
    build:
      context: .
      dockerfile: Dockerfile-UI
    command: serve -s build -l 8080
    ports:
      - "8080:8080"
    depends_on:
      - api