FROM node:10

RUN mkdir /code
WORKDIR /code
# Install dependencies
# package*.json used to copy files package.json and package-lock.json
COPY Frontend ./
RUN apt-get update
RUN apt-get install -y xsel
RUN npm i --save
RUN npm install -g serve
# ARG LOCAL_URL_API
# ENV LOCAL_URL_API=${LOCAL_URL_API}
RUN npm run build
