environment: 'test'
production:
    greenwich_meta:
        API_NAME:
        BASE_URL:
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
    greenwich_occ:
        API_NAME:
        BASE_URL:
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
    lisbon:
        API_NAME:
        BASE_URL:
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
    milan:
        API_NAME:
        BASE_URL:
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
test:
    greenwich_meta:
        API_NAME: "Greenwich_SmartParking_Meta"
        BASE_URL: 
            > 
                https://maps.london.gov.uk/gla/rest/services/apps/
                smart_parking_demo_service_01/MapServer/0/query?where=1%3D1&text=
                &objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope
                &inSR=&spatialRel=esriSpatialRelIntersects&relationParam=
                &outFields=*&returnGeometry=true&returnTrueCurves=false
                &maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=
                &outStatistics=&returnZ=false&returnM=false&gdbVersion=
                &returnDistinctValues=false&resultOffset=&resultRecordCount=
                &queryByDistance=&returnExtentsOnly=false&datumTransformation=
                &parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME: 300
        API_KEY: "5gVq3ybH3iOAMmC5xDt1ibuDXvBjpvNOA7X6se78bbU-a6pumBR3avSvcjtLIpQq"
        TOKEN_EXPIRY: "01/01/2019 00:00:00"
        REFRESH_URL: "https://maps.london.gov.uk/gla/tokens/generateToken"
        API_CLASS: "importers.greenwich.GreenwichMeta"
    greenwich_occ:
        API_NAME: "Greenwich_SmartParking_OCC"
        BASE_URL: 
            >
                https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/1/query?
                where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=
                &spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true
                &returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false
                &returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=
                &returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.greenwich.GreenwichOCC"
    greenwich_kiwi:
        API_NAME: "Greenwich_ErnestDence_pump"
        BASE_URL: 
            >
                https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/6/query?
                where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=
                &spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true
                &returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false
                &returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=
                &returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME: 36000000
        API_KEY: 
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.greenwich.GreenwichKiwiPump"
    greenwich_kiwi_house:
        API_NAME: "Greenwich_wholehouse"
        BASE_URL: 
            >
                https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/4/query?
                where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=
                &spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true
                &returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false
                &returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=
                &returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME: 36000000
        API_KEY: 
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.greenwich.GreenwichWholeHouse"
    greenwich_meta_2:
        API_NAME: "Greenwich_SmartParking_Meta_2"
        BASE_URL: 
            > 
                https://maps.london.gov.uk/gla/rest/services/apps/
                smart_parking_demo_service_01/MapServer/7/query?where=1%3D1&text=
                &objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope
                &inSR=&spatialRel=esriSpatialRelIntersects&relationParam=
                &outFields=*&returnGeometry=true&returnTrueCurves=false
                &maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=
                &outStatistics=&returnZ=false&returnM=false&gdbVersion=
                &returnDistinctValues=false&resultOffset=&resultRecordCount=
                &queryByDistance=&returnExtentsOnly=false&datumTransformation=
                &parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME: 300
        API_KEY: 
        TOKEN_EXPIRY: "01/01/2019 00:00:00"
        REFRESH_URL: "https://maps.london.gov.uk/gla/tokens/generateToken"
        API_CLASS: "importers.greenwich.GreenwichMeta_2"
    greenwich_occ_2:
        API_NAME: "Greenwich_SmartParking_OCC_2"
        BASE_URL: 
            >
                https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/8/query?
                where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=
                &spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true
                &returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false
                &returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=
                &returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME:
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.greenwich.GreenwichOCC_2"
    greenwich_siemens:
        API_NAME: "Greenwich_Siemens"
        BASE_URL: 
            >
                https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/3/query?
                where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=
                &spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true
                &returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false
                &returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false
                &returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=
                &returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
        REFRESH_TIME: 36000000
        API_KEY:
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.greenwich.GreenwichSiemens"
    air_quality:
        API_NAME: "Air_Quality_KCL"
        BASE_URL: 
            >
                http://api.erg.kcl.ac.uk/AirQuality/Data/Site/SiteCode=%s/StartDate=%s/EndDate=%s/Json
        REFRESH_TIME: 3600
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.air_quality.KCLAirQuality"
    tfl_bike_points:
       API_NAME: "TfL_BikePoints"
       BASE_URL:
           >
               https://api.tfl.gov.uk/BikePoint/
       REFRESH_TIME: 300
       API_KEY: ""
       TOKEN_EXPIRY:
       REFRESH_URL:
       API_CLASS: "importers.tfl_bike_points.TfL_BikePoints"
    lisbon:
        API_NAME: "Lisbon_API"
        BASE_URL: "https://iot.alticelabs.com/api/subscriptions/4daef3d5-61f4-4382-9a9b-a8495a34d079/values"
        REFRESH_TIME: 3600
        API_KEY: ""
        USER_NAME: "fcc_subscriber"
        USER_PASSCODE: "bb9064b2be77226cfc263dd2880742ae91f9c7d5"
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.lisbon.LisbonAPI"
    milan:
        API_NAME: "Milan_API"
        BASE_URL: "http://supernovalora.a2asmartcity.io/api/v2/devices"
        REFRESH_TIME: 3600
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        API_CLASS: "importers.milan.MilanAPI"
    milan_sensori_meteo_meta:
        API_NAME: "Milan_API_sensori_meteo_meta"
        BASE_URL: "https://api.comune.milano.it:443/SC_LAMPPOST_SensoriMeteo/1.0/dati_meteo?"
        REFRESH_TIME: 86400
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        HEADERS: "{'Accept': 'application/json', 'Authorization': 'Bearer 90dbba2b-ce2d-31f6-9bdb-71b08b4548c1'}"
        API_CLASS: "importers.milan.Milan_API_sensori_meteo"
    milan_sensori_meteo:
        API_NAME: "Milan_API_sensori_meteo"
        BASE_URL: "https://api.comune.milano.it:443/SC_LAMPPOST_SensoriMeteo/1.0/dati_meteo?"
        REFRESH_TIME: 86400
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        HEADERS: "{'Accept': 'application/json', 'Authorization': 'Bearer 90dbba2b-ce2d-31f6-9bdb-71b08b4548c1'}"
        API_CLASS: "importers.milan.Milan_API_sensori_meteo"
    milan_sc_parking_kiunsys_meta:
        API_NAME: "Milan_API_sc_parking_kiunsys_meta"
        BASE_URL: "https://api.comune.milano.it:443/SC_PARKING_Kiunsys/1.0/parkingAreas"
        REFRESH_TIME: 86400
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        HEADERS: "{'Accept': 'application/json', 'Authorization': 'Bearer 54d53fac-5903-3d78-b2a0-89b3200e79d2'}"
        API_CLASS: "importers.milan.Milan_API_sc_parking_kiunsys_meta"
    milan_sc_parking_kiunsys:
        API_NAME: "Milan_API_sc_parking_kiunsys"
        BASE_URL: "https://api.comune.milano.it:443/SC_PARKING_Kiunsys/1.0/parkingArea/SHCS02001/parkingSpotSensorsStatus?"
        REFRESH_TIME: 60
        API_KEY: ""
        TOKEN_EXPIRY:
        REFRESH_URL:
        HEADERS: "{'Accept': 'application/json', 'Authorization': 'Bearer 54d53fac-5903-3d78-b2a0-89b3200e79d2'}"
        API_CLASS: "importers.milan.Milan_API_sc_parking_kiunsys"
    kcl_aq:
        API_NAME: "AirQuality"
        BASE_URL: "http://api.erg.kcl.ac.uk/AirQuality/Annual/MonitoringObjective/GroupName=London/Year=2010/Json"
        REFRESH_TIME: 3600
        API_KEY: None
        TOKEN_EXPIRY: None
        REFRESH_URL:
        API_CLASS: 