apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcc-api
spec:
  selector:
    matchLabels:
      component: fcc-api
  template:
    metadata:
      labels:
        component: fcc-api
    spec:
      containers:
      - name: fcc-api
        image: <<api-image-details>>
        args:
        - python
        - manage.py
        - gunicorn
        ports:
        - containerPort: 5000
          protocol: TCP
      - name: redis
        image: <<api-image-details>>
        args:
        - redis-server
        ports:
        - containerPort: 6379
          protocol: TCP
      - name: celery
        image: <<api-image-details>>
        args:
        - celery
        - -A
        - manage.celery_task
        - worker
        - -l
        - info
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: LoadBalancer
  selector:
    component: fcc-api
  ports:
    - name: "api"
      port: 80
      targetPort: 5000
    - name: "redis"
      port: 6379
      targetPort: 6379
