apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcc-db
spec:
  selector:
    matchLabels:
      component: fcc-db
  template:
    metadata:
      labels:
        app: fcc-db
        component: fcc-db
    spec:
      containers:
        - name: fcc-db
          image: gcr.io/dotmodus/fcc/db:v0.1
          # imagePullPolicy: Never
          volumeMounts:
            - name: pg-claim-mount
              mountPath: /var/lib/postgresql
      volumes:
        - name: pg-claim-mount
          persistentVolumeClaim:
            claimName: pg-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  type: ClusterIP
  selector:
    component: fcc-db
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  labels:
    type: local
    app: fcc-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  labels:
    app: fcc-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
