FROM ubuntu:16.04

RUN apt-get update && apt-get -y install sudo
RUN apt-get install -y libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev

RUN sudo apt-get update && apt-get -y install postgresql postgresql-client postgresql-contrib
RUN sudo apt-get -y install postgis


USER postgres
RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER sharingcities WITH SUPERUSER PASSWORD 'sharingcities';" &&\
    createdb -O sharingcities analytics &&\
    psql -d analytics -c "CREATE EXTENSION postgis;"


RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.5/main/pg_hba.conf
RUN echo "listen_addresses = '*'" >> /etc/postgresql/9.5/main/postgresql.conf

EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
CMD ["/usr/lib/postgresql/9.5/bin/postgres", "-D", "/var/lib/postgresql/9.5/main", "-c", "config_file=/etc/postgresql/9.5/main/postgresql.conf"]