version: '3'

services:
  db:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile-DB
    restart: on-failure
  api:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile-API
    command: bash -c "sleep 7; python manage.py gunicorn & service redis-server start & celery -A manage.celery_task worker -l info"
    volumes:
      - ../../Analytics/:/Analytics
    ports:
      - "8000:5000"
      - "6379:6379"
    depends_on:
      - db
    restart: on-failure
  ui:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile-UI
    command: serve -s build -l 8080
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: on-failure