FROM python:3.7

# Create a Work Directory for the Code
RUN mkdir /Analytics
WORKDIR /Analytics
COPY Analytics .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y redis-server
