apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fcc-ingress
spec:
  rules:
  - host: ui.35.244.139.79.xip.io
    http:
      paths:
      - backend:
          serviceName: ui-svc
          servicePort: 8080
  - host: api.35.246.41.23.xip.io
    http:
      paths:
      - backend:
          serviceName: api-svc
          servicePort: 5000
