apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fcc-ingress
spec:
  rules:
  # - host: ui.fcc.com
  - http:
      paths:
      - backend:
          serviceName: ui-svc
          servicePort: 8080
  # - host: api.fcc.com
  - http:
      paths:
      - backend:
          serviceName: api-svc
          servicePort: 5000
