// config
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_CONFIG_FULFILLED = 'FETCH_CONFIG_FULFILLED';
export const FETCH_CONFIG_REJECTED = 'FETCH_CONFIG_REJECTED';

// data
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';
export const PURGE_DATA = 'PURGE_DATA';

// editor
export const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';
export const PURGE_EDITOR = 'PURGE_EDITOR';

// grid
export const FETCH_LAYOUT = 'FETCH_LAYOUT';
export const FETCH_LAYOUT_FULFILLED = 'FETCH_LAYOUT_FULFILLED';
export const FETCH_LAYOUT_REJECTED = 'FETCH_LAYOUT_REJECTED';

// sources
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_FULFILLED = 'FETCH_SOURCES_FULFILLED';
export const FETCH_SOURCES_REJECTED = 'FETCH_SOURCES_REJECTED';
export const TOGGLE_SOURCE_SELECTED = 'TOGGLE_SOURCE_SELECTED';

// themes
export const FETCH_THEMES = 'FETCH_THEMES';
export const FETCH_THEMES_FULFILLED = 'FETCH_THEMES_FULFILLED';
export const FETCH_THEMES_REJECTED = 'FETCH_THEMES_REJECTED';
export const TOGGLE_THEME_SELECTED = 'TOGGLE_THEME_SELECTED';

// user auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// widgets
export const FETCH_WIDGETS = 'FETCH_WIDGETS';
export const FETCH_WIDGETS_FULFILLED = 'FETCH_WIDGETS_FULFILLED';
export const FETCH_WIDGETS_REJECTED = 'FETCH_WIDGETS_REJECTED';
