// grid
export const FETCH_LAYOUT = 'FETCH_LAYOUT';
export const FETCH_LAYOUT_FULFILLED = 'FETCH_LAYOUT_FULFILLED';
export const FETCH_LAYOUT_REJECTED = 'FETCH_LAYOUT_REJECTED';

// source
export const FETCH_SOURCE_DATA = 'FETCH_SOURCE_DATA';
export const FETCH_SOURCE_DATA_FULFILLED = 'FETCH_SOURCE_DATA_FULFILLED';
export const FETCH_SOURCE_DATA_REJECTED = 'FETCH_SOURCE_DATA_REJECTED';

// sources
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_FULFILLED = 'FETCH_SOURCES_FULFILLED';
export const FETCH_SOURCES_REJECTED = 'FETCH_SOURCES_REJECTED';

// themes
export const FETCH_THEMES = 'FETCH_THEMES';
export const FETCH_THEMES_FULFILLED = 'FETCH_THEMES_FULFILLED';
export const FETCH_THEMES_REJECTED = 'FETCH_THEMES_REJECTED';

// user auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// widgets
export const FETCH_WIDGETS = 'FETCH_WIDGET';
export const FETCH_WIDGETS_FULFILLED = 'FETCH_WIDGET_FULFILLED';
export const FETCH_WIDGETS_REJECTED = 'FETCH_WIDGET_REJECTED';
