api_endpoints:
  air_quality:
    API_CLASS: importers.air_quality.KCLAirQuality
    API_KEY: ''
    API_NAME: Air_Quality_KCL
    BASE_URL: http://api.erg.kcl.ac.uk/AirQuality/Data/Site/SiteCode=%s/StartDate=%s/EndDate=%s/Json
    REFRESH_TIME: 3600
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  gla_template_importer:
    API_CLASS: importers.greenwich.GLATemplateImporter
    API_KEY: ''
    API_NAME: GLA_template
    BASE_URL: https://data.london.gov.uk/api/table/9080r_yhdps
    REFRESH_TIME: 36000000
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  greenwich_kiwi:
    API_CLASS: importers.greenwich.GreenwichKiwiPump
    API_KEY: null
    API_NAME: Greenwich_ErnestDence_pump
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/6/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: 36000000
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  greenwich_kiwi_house:
    API_CLASS: importers.greenwich.GreenwichWholeHouse
    API_KEY: null
    API_NAME: Greenwich_wholehouse
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/4/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: 36000000
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  greenwich_meta:
    API_CLASS: importers.greenwich.GreenwichMeta
    API_KEY: 5gVq3ybH3iOAMmC5xDt1ibuDXvBjpvNOA7X6se78bbU-a6pumBR3avSvcjtLIpQq
    API_NAME: Greenwich_SmartParking_Meta
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: 300
    REFRESH_URL: https://maps.london.gov.uk/gla/tokens/generateToken
    TOKEN_EXPIRY: 01/01/2019 00:00:00
  greenwich_meta_2:
    API_CLASS: importers.greenwich.GreenwichMeta_2
    API_KEY: null
    API_NAME: Greenwich_SmartParking_Meta_2
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/7/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: 300
    REFRESH_URL: https://maps.london.gov.uk/gla/tokens/generateToken
    TOKEN_EXPIRY: 01/01/2019 00:00:00
  greenwich_occ:
    API_CLASS: importers.greenwich.GreenwichOCC
    API_KEY: null
    API_NAME: Greenwich_SmartParking_OCC
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: null
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  greenwich_occ_2:
    API_CLASS: importers.greenwich.GreenwichOCC_2
    API_KEY: null
    API_NAME: Greenwich_SmartParking_OCC_2
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/8/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: null
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  greenwich_siemens:
    API_CLASS: importers.greenwich.GreenwichSiemens
    API_KEY: null
    API_NAME: Greenwich_Siemens
    BASE_URL: https://maps.london.gov.uk/gla/rest/services/apps/smart_parking_demo_service_01/MapServer/3/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=pjson&token=
    REFRESH_TIME: 36000000
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  lisbon:
    API_CLASS: importers.lisbon.LisbonAPI
    API_KEY: ''
    API_NAME: Lisbon_API
    BASE_URL: https://iot.alticelabs.com/api/subscriptions/4daef3d5-61f4-4382-9a9b-a8495a34d079/values
    REFRESH_TIME: 3600
    REFRESH_URL: null
    TOKEN_EXPIRY: null
    USER_NAME: fcc_subscriber
    USER_PASSCODE: bb9064b2be77226cfc263dd2880742ae91f9c7d5
  milan:
    API_CLASS: importers.milan.MilanAPI
    API_KEY: ''
    API_NAME: Milan_API
    BASE_URL: http://supernovalora.a2asmartcity.io/api/v2/devices
    REFRESH_TIME: 3600
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  milan_sc_emobility_refeel:
    API_CLASS: importers.milan.Milan_API_sc_emobility_refeel
    API_KEY: ''
    API_NAME: Milan_API_sc_emobility_refeel
    BASE_URL: https://api.comune.milano.it:443/SC_EMOBILITY_Refeel/1.0/vehiclesstatus?
    HEADERS: '{''Accept'': ''application/json'', ''Authorization'': ''Bearer 54d53fac-5903-3d78-b2a0-89b3200e79d2''}'
    REFRESH_TIME: 60
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  milan_sc_parking_kiunsys:
    API_CLASS: importers.milan.Milan_API_sc_parking_kiunsys
    API_KEY: ''
    API_NAME: Milan_API_sc_parking_kiunsys
    BASE_URL: https://api.comune.milano.it:443/SC_PARKING_Kiunsys/1.0/parkingArea/SHCS02001/parkingSpotSensorsStatus?
    HEADERS: '{''Accept'': ''application/json'', ''Authorization'': ''Bearer 54d53fac-5903-3d78-b2a0-89b3200e79d2''}'
    REFRESH_TIME: 60
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  milan_sc_parking_kiunsys_meta:
    API_CLASS: importers.milan.Milan_API_sc_parking_kiunsys_meta
    API_KEY: ''
    API_NAME: Milan_API_sc_parking_kiunsys_meta
    BASE_URL: https://api.comune.milano.it:443/SC_PARKING_Kiunsys/1.0/parkingAreas
    HEADERS: '{''Accept'': ''application/json'', ''Authorization'': ''Bearer 54d53fac-5903-3d78-b2a0-89b3200e79d2''}'
    REFRESH_TIME: 86400
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  milan_sensori_meteo:
    API_CLASS: importers.milan.Milan_API_sensori_meteo
    API_KEY: ''
    API_NAME: Milan_API_sensori_meteo
    BASE_URL: https://api.comune.milano.it:443/SC_LAMPPOST_SensoriMeteo/1.0/dati_meteo?
    HEADERS: '{''Accept'': ''application/json'', ''Authorization'': ''Bearer 90dbba2b-ce2d-31f6-9bdb-71b08b4548c1''}'
    REFRESH_TIME: 86400
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  milan_sensori_meteo_meta:
    API_CLASS: importers.milan.Milan_API_sensori_meteo
    API_KEY: ''
    API_NAME: Milan_API_sensori_meteo_meta
    BASE_URL: https://api.comune.milano.it:443/SC_LAMPPOST_SensoriMeteo/1.0/dati_meteo?
    HEADERS: '{''Accept'': ''application/json'', ''Authorization'': ''Bearer 90dbba2b-ce2d-31f6-9bdb-71b08b4548c1''}'
    REFRESH_TIME: 86400
    REFRESH_URL: null
    TOKEN_EXPIRY: null
  tfl_bike_points:
    API_CLASS: importers.tfl_bike_points.TfL_BikePoints
    API_KEY: ''
    API_NAME: TfL_BikePoints
    BASE_URL: https://api.tfl.gov.uk/BikePoint/
    REFRESH_TIME: 300
    REFRESH_URL: null
    TOKEN_EXPIRY: null
celery:
  BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/0
flask_server:
  host: api
  passthrough_errors: false
  port: 5000
  processes: 1
  ssl_crt: null
  ssl_key: null
  threaded: false
  use_debugger: null
  use_reloader: null
gunicorn_server:
  gunicorn_host: api
  gunicorn_port: 5000
  gunicorn_workers: 4
jwt_auth:
  JWT_BLACKLIST_ENABLED: true
  JWT_BLACKLIST_TOKEN_CHECKS:
  - access
  - refresh
  JWT_SECRET_KEY: jwt-secret-string
postgres:
  DEBUG: true
  SECRET_KEY: test-secret-key
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  db_host: db
  db_name: test_analytics
  db_password: sharingcities
  db_psql_base_uri: postgresql+psycopg2
  db_sql_base_uri: mysql+pymysql
  db_username: sharingcities
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://sharingcities:sharingcities@localhost/test_analytics
sendgrid:
  api_key: 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
  email_subject: Sharing Cities - Forgot Password
  html_template: forgot_password_email.html
  sender_email: sharedcitiestesting@gmail.com
  system_password_length: 15
  text_template: 'Hi {username}

    You requested for your password to be reset. Your new system generated password
    is : {password} You can now login to the Sharing Cities Dashboard with this password.

    It is recommended you change your password once logged in.

    '

NODE_ENV: development
NODE_HOST: http://localhost
NODE_API_PORT: :5000
NODE_DEV_PORT: :8080