api_endpoints:
  air_quality:
    API_CLASS: importers.air_quality.KCLAirQuality
    API_KEY: ''
    API_NAME: Air_Quality_KCL
    BASE_URL: http://api.erg.kcl.ac.uk/AirQuality/Data/Site/SiteCode=%s/StartDate=%s/EndDate=%s/Json
    REFRESH_TIME: 3600
    REFRESH_URL: null
    TOKEN_EXPIRY: null
celery:
  BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/0
flask_server:
  host: 0.0.0.0
  passthrough_errors: false
  port: 5000
  processes: 1
  ssl_crt: null
  ssl_key: null
  threaded: true
  use_debugger: null
  use_reloader: null
gunicorn_server:
  gunicorn_host: 0.0.0.0
  gunicorn_port: 5000
  gunicorn_workers: 4
jwt_auth:
  JWT_BLACKLIST_ENABLED: true
  JWT_BLACKLIST_TOKEN_CHECKS:
  - access
  - refresh
  JWT_SECRET_KEY: jwt-secret-string
postgres:
  DEBUG: true
  SECRET_KEY: test-secret-key
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  db_host: localhost
  db_name: analytics
  db_password: sharingcities
  db_psql_base_uri: postgresql+psycopg2
  db_sql_base_uri: mysql+pymysql
  db_username: sharingcities
sendgrid:
  api_key: <SENDGRID_API_KEY>
  email_subject: Sharing Cities - Forgot Password
  html_template: forgot_password_email.html
  sender_email: sharedcitiestesting@gmail.com
  system_password_length: 15
  text_template: 'Hi {username}

    You requested for your password to be reset. Your new system generated password
    is : {password} You can now login to the Sharing Cities Dashboard with this password.

    It is recommended you change your password once logged in.

    '
alert:
  email_subject: Sharing Cities - Alert
  html_template: alert_email.html
  sender_email: sharedcitiestesting@gmail.com
  text_template: 'Hi {username}

    You have set an alert on the Sharing Cities Dashboard for {attribute}
    with a threshold value of {threshold}.
    This email is to inform you that sensor {sensor_id} at latitude:{lat} and
    longitude:{lon} recorded a value {value} on {recorded_date} which
    {verb} your threshold by {diff}.

    '
NODE_ENV: development
API_HOST: /api