// config
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_CONFIG_FULFILLED = 'FETCH_CONFIG_FULFILLED';
export const FETCH_CONFIG_REJECTED = 'FETCH_CONFIG_REJECTED';

// data
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';
export const PURGE_DATA = 'PURGE_DATA';

// editor
export const SET_MAP_CAN_MAP = 'SET_MAP_CAN_MAP';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_MAP_DATA = 'SET_MAP_DATA';
export const SET_MAP_HEATMAP_ATTRIBUTE = 'SET_MAP_HEATMAP_ATTRIBUTE';
export const SET_MAP_SHOW_HEATMAP = 'SET_MAP_SHOW_HEATMAP';
export const SET_MAP_TILE_LAYER = 'SET_MAP_TILE_LAYER';
export const SET_MAP_ZOOM = 'SET_MAP_ZOOM';
export const SET_PLOT_DATA = 'SET_PLOT_DATA';
export const SET_PLOT_DESCRIPTION = 'SET_PLOT_DESCRIPTION';
export const SET_PLOT_ENCODING = 'SET_PLOT_ENCODING';
export const SET_PLOT_TYPE = 'SET_PLOT_TYPE';
export const SET_WIDGET_NAME = 'SET_WIDGET_NAME';
export const SET_WIDGET_TYPE = 'SET_WIDGET_TYPE';
export const PURGE_EDITOR = 'PURGE_EDITOR';

// grid
export const FETCH_LAYOUT = 'FETCH_LAYOUT';
export const FETCH_LAYOUT_FULFILLED = 'FETCH_LAYOUT_FULFILLED';
export const FETCH_LAYOUT_REJECTED = 'FETCH_LAYOUT_REJECTED';

// sources
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_FULFILLED = 'FETCH_SOURCES_FULFILLED';
export const FETCH_SOURCES_REJECTED = 'FETCH_SOURCES_REJECTED';
export const TOGGLE_SOURCE_SELECTED = 'TOGGLE_SOURCE_SELECTED';

// themes
export const FETCH_THEMES = 'FETCH_THEMES';
export const FETCH_THEMES_FULFILLED = 'FETCH_THEMES_FULFILLED';
export const FETCH_THEMES_REJECTED = 'FETCH_THEMES_REJECTED';
export const TOGGLE_THEME_SELECTED = 'TOGGLE_THEME_SELECTED';

// user auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// widgets
export const FETCH_WIDGETS = 'FETCH_WIDGETS';
export const FETCH_WIDGETS_FULFILLED = 'FETCH_WIDGETS_FULFILLED';
export const FETCH_WIDGETS_REJECTED = 'FETCH_WIDGETS_REJECTED';
